export const FETCH_DATA_FROM_API = 'FETCH_DATA_FROM_API'
export const LINK_FOR_FETCHING_TOKENS_FROM_API =
  'LINK_FOR_FETCHING_TOKENS_FROM_API'
export const LINK_FOR_FETCHING_EXCHANGE_MINORS_FROM_API =
  'LINK_FOR_FETCHING_EXCHANGE_MINORS_FROM_API'
export const LINK_FOR_FETCHING_USERS_EXCHANGE_FROM_API =
  'LINK_FOR_FETCHING_USERS_EXCHANGE_FROM_API'
export const LINK_FOR_FETCHING_CHAT_ROOM_FROM_API =
  'LINK_FOR_FETCHING_CHAT_ROOM_FROM_API'
export const LINK_FOR_FETCHING_ALL_MINORS_FROM_API =
  'LINK_FOR_FETCHING_ALL_MINORS_FROM_API'
export const LINK_FOR_FETCHING_USERS_DATA_FROM_API =
  'LINK_FOR_FETCHING_USERS_DATA_FROM_API'
export const LINK_FOR_FETCHING_MAIN_SCREEN_DATA_FROM_API =
  'LINK_FOR_FETCHING_MAIN_SCREEN_DATA_FROM_API'
export const LINK_FOR_GUEST_FROM_API = 'LINK_FOR_GUEST_FROM_API'

export const LOG_IN = 'LOG_IN'
