export const FETCH_DATA_FROM_API = 'FETCH_DATA_FROM_API'
export const LINK_FOR_FETCHING_TOKENS_FROM_API =
  'LINK_FOR_FETCHING_TOKENS_FROM_API'
export const LINK_FOR_FETCHING_EXCHANGE_MINORS_FROM_API =
  'LINK_FOR_FETCHING_EXCHANGE_MINORS_FROM_API'
export const LINK_FOR_FETCHING_USERS_EXCHANGE_FROM_API =
  'LINK_FOR_FETCHING_USERS_EXCHANGE_FROM_API'
export const LINK_FOR_FETCHING_CHAT_ROOM_FROM_API =
  'LINK_FOR_FETCHING_CHAT_ROOM_FROM_API'
export const LINK_FOR_FETCHING_ALL_MINORS_FROM_API =
  'LINK_FOR_FETCHING_ALL_MINORS_FROM_API'
export const LINK_FOR_FETCHING_USERS_DATA_FROM_API =
  'LINK_FOR_FETCHING_USERS_DATA_FROM_API'
export const LINK_FOR_FETCHING_MAIN_SCREEN_DATA_FROM_API =
  'LINK_FOR_FETCHING_MAIN_SCREEN_DATA_FROM_API'
export const LINK_FOR_GUEST_FROM_API = 'LINK_FOR_GUEST_FROM_API'
export const LINK_FOR_LOG_IN_FROM_API = 'LINK_FOR_LOG_IN_FROM_API'
export const LINK_FOR_LOG_OUT = 'LINK_FOR_LOG_OUT'
export const LINK_TO_NEW_MESSAGE = 'LINK_TO_NEW_MESSAGE'
export const SEND_MESSAGE = 'SEND_MESSAGE'

//login and registration
export const LINK_TO_LOG_IN = 'LINK_TO_LOG_IN'
export const LINK_FOR_CHANGE_PROFILE_DATA = 'LINK_FOR_CHANGE_PROFILE_DATA'

export const CHANGE_PROFILE = 'CHANGE_PROFILE'

export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'
