export const GET_TOKEN_FROM_DB = 'GET_TOKEN_FROM_DB'
export const UPDATE_TOKEN_IN_DB = 'UPDATE_TOKEN_IN_DB'
export const UPDATE_AUTH_TOKEN_IN_DB = 'UPDATE_AUTH_TOKEN_IN_DB'
export const REMOVE_TOKENS = 'REMOVE_TOKENS'
